### ISSUE TITLE
example config

### ISSUE THREAD

**Issue by AlunR** [nirmaljingar/CI-DB-Driver-for-SQL-Anywhere#1]
Could you provide an example config for this database driver please?

My server runs on a different port so that would be useful

**Comment by nirmaljingar** [comment]
Here is the database conf:

$active_group = 'default';
$active_record = TRUE;

$db['default']['hostname'] = 'localhost';
$db['default']['username'] = '***_';
$db['default']['password'] = '**_*';
$db['default']['database'] = 'soa_local';
$db['default']['server_name'] = 'soa_local';
$db['default']['dbdriver'] = 'sasql';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = TRUE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
$db['default']['swap_pre'] = '';
$db['default']['autoinit'] = TRUE;
$db['default']['stricton'] = FALSE;
